### ISSUE TITLE
Cannot find dataset associated with vignette 5

### ISSUE THREAD

**Issue by jRafi** [gerkovink/miceVignettes#3]
Part 5 of the mice vignettes seems to have a problem with missing data(set).

Although, the `popular` data set from Hox can be found at his website, the file `popular.RData` and it's associated objects seems to be not included in the package.

I really appreciate the vignettes!
Best,
Jonas

EDIT: Noticed that you can find it on github, perhaps just add a link?

**Comment by gerkovink** [comment]
Run the following lines.
```r
con <- url("https://www.gerkovink.com/mimp/popular.RData")
load(con)
```

All the best,

Gerko
